const Map<String, List<List<String>>> gamesByCategory = {
  "Ação": [
    ["Call of Duty", "assets/images/games/Call of Duty.jpg"],
    ["Grand Theft Auto", "assets/images/games/Grand Theft Auto.jpg"],
    ["Assassin's Creed", "assets/images/games/Assassin's Creed.jpg"],
    ["Uncharted", "assets/images/games/Uncharted.jpg"],
  ],
  "Estratégia": [
    ["Age of Empires", "assets/images/games/Age of Empires.jpg"],
    ["Civilization", "assets/images/games/Civilization.jpg"],
    ["Starcraft", "assets/images/games/Starcraft.jpg"],
    ["Command & Conquer", "assets/images/games/Command & Conquer.jpg"],
  ],
  "Aventura": [
    ["The Legend of Zelda", "assets/images/games/the-witcher.jpg"],
    ["Tomb Raider", "assets/images/games/the-witcher.jpg"],
    ["Prince of Persia", "assets/images/games/the-witcher.jpg"],
    ["Journey", "assets/images/games/the-witcher.jpg"],
  ],
  "RPG": [
    ["Final Fantasy", "assets/images/games/the-witcher.jpg"],
    ["The Witcher", "assets/images/games/the-witcher.jpg"],
    ["Mass Effect", "assets/images/games/the-witcher.jpg"],
    ["Elder Scrolls", "assets/images/games/the-witcher.jpg"],
  ],
  "Esportes": [
    ["FIFA", "assets/images/games/the-witcher.jpg"],
    ["NBA 2K", "assets/images/games/the-witcher.jpg"],
    ["Madden NFL", "assets/images/games/the-witcher.jpg"],
    ["WWE", "assets/images/games/the-witcher.jpg"],
  ],
  "Corrida": [
    ["Need for Speed", "assets/images/games/the-witcher.jpg"],
    ["Forza Horizon", "assets/images/games/the-witcher.jpg"],
    ["Gran Turismo", "assets/images/games/the-witcher.jpg"],
    ["Dirt", "assets/images/games/the-witcher.jpg"],
  ],
  "Simulação": [
    ["The Sims", "assets/images/games/the-witcher.jpg"],
    ["SimCity", "assets/images/games/the-witcher.jpg"],
    ["Flight Simulator", "assets/images/games/the-witcher.jpg"],
    ["Euro Truck Simulator", "assets/images/games/the-witcher.jpg"],
  ],
  "Tiro": [
    ["Call of Duty", "assets/images/games/the-witcher.jpg"],
    ["Battlefield", "assets/images/games/the-witcher.jpg"],
    ["Halo", "assets/images/games/the-witcher.jpg"],
    ["Doom", "assets/images/games/the-witcher.jpg"],
  ],
  "Luta": [
    ["Mortal Kombat", "assets/images/games/the-witcher.jpg"],
    ["Street Fighter", "assets/images/games/the-witcher.jpg"],
    ["Tekken", "assets/images/games/the-witcher.jpg"],
    ["Dragon Ball FighterZ", "assets/images/games/the-witcher.jpg"],
  ],
  "Quebra-cabeça": [
    ["Tetris", "assets/images/games/the-witcher.jpg"],
    ["Bejeweled", "assets/images/games/the-witcher.jpg"],
    ["Candy Crush", "assets/images/games/the-witcher.jpg"],
    ["Myst", "assets/images/games/the-witcher.jpg"],
  ],
  "Plataforma": [
    ["Super Mario Bros", "assets/images/games/the-witcher.jpg"],
    ["Sonic the Hedgehog", "assets/images/games/the-witcher.jpg"],
    ["Crash Bandicoot", "assets/images/games/the-witcher.jpg"],
    ["Rayman", "assets/images/games/the-witcher.jpg"],
  ],
  "Sobrevivência": [
    ["Minecraft", "assets/images/games/the-witcher.jpg"],
    ["Don't Starve", "assets/images/games/the-witcher.jpg"],
    ["ARK: Survival Evolved", "assets/images/games/the-witcher.jpg"],
    ["Subnautica", "assets/images/games/the-witcher.jpg"],
  ],
  "Mundo aberto": [
    ["Grand Theft Auto", "assets/images/games/the-witcher.jpg"],
    ["Red Dead Redemption", "assets/images/games/the-witcher.jpg"],
    ["The Elder Scrolls", "assets/images/games/the-witcher.jpg"],
    ["Assassin's Creed", "assets/images/games/the-witcher.jpg"],
  ],
  "MMORPG": [
    ["World of Warcraft", "assets/images/games/the-witcher.jpg"],
    ["Guild Wars", "assets/images/games/the-witcher.jpg"],
    ["Final Fantasy XIV", "assets/images/games/the-witcher.jpg"],
    ["EVE Online", "assets/images/games/the-witcher.jpg"],
  ],
  "Musical": [
    ["Guitar Hero", "assets/images/games/the-witcher.jpg"],
    ["Rock Band", "assets/images/games/the-witcher.jpg"],
    ["Just Dance", "assets/images/games/the-witcher.jpg"],
    ["Dance Dance Revolution", "assets/images/games/the-witcher.jpg"],
  ],
  "Casual": [
    ["Angry Birds", "assets/images/games/the-witcher.jpg"],
    ["Fruit Ninja", "assets/images/games/the-witcher.jpg"],
    ["Plants vs Zombies", "assets/images/games/the-witcher.jpg"],
    ["Doodle Jump", "assets/images/games/the-witcher.jpg"],
  ],
  "Educacional": [
    ["Math Blaster", "assets/images/games/the-witcher.jpg"],
    ["Reader Rabbit", "assets/images/games/the-witcher.jpg"],
    ["Where in the World is Carmen Sandiego?", "assets/images/the-witcher/nome.jpg"],
    ["The Oregon Trail", "assets/images/games/the-witcher.jpg"],
  ],
  "Infantil": [
    ["Super Mario Bros", "assets/images/games/the-witcher.jpg"],
    ["Sonic the Hedgehog", "assets/images/games/the-witcher.jpg"],
    ["Crash Bandicoot", "assets/images/games/the-witcher.jpg"],
    ["Rayman", "assets/images/games/the-witcher.jpg"],
  ],
  "Cartas": [
    ["Poker", "assets/images/games/the-witcher.jpg"],
    ["Solitaire", "assets/images/games/the-witcher.jpg"],
    ["Magic: The Gathering", "assets/images/games/the-witcher.jpg"],
    ["Yu-Gi-Oh!", "assets/images/the-witcher/nome.jpg"],
  ],
  "Tabuleiro": [
    ["Monopoly", "assets/images/games/the-witcher.jpg"],
    ["Risk", "assets/images/games/the-witcher.jpg"],
    ["Chess", "assets/images/games/the-witcher.jpg"],
    ["Settlers of Catan", "assets/images/games/the-witcher.jpg"],
  ],
};
